# Generated by Django 2.0.1 on 2018-01-28 12:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип расходника')),
            ],
            options={
                'verbose_name': 'Тип расходника',
                'verbose_name_plural': 'Типы расходников',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фирмы')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
            },
        ),
        migrations.CreateModel(
            name='MoveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(blank=True, help_text='Указывайте дату только тогда,  когда приходит материал на склад', null=True, verbose_name='Дата прихода')),
                ('date_out', models.DateField(blank=True, help_text='Указывайте дату только тогда, материал уходит со склада', null=True, verbose_name='Дата ухода')),
                ('count', models.IntegerField(help_text='Ставьте "-" перед количеством для выдачи товара,\nоставляйте положительным для поступления на склад', verbose_name='Количество')),
                ('tip', models.TextField(verbose_name='Заметка')),
                ('user', models.CharField(blank=True, help_text='Указывается только при расходе материала', max_length=255, verbose_name='Установил')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.ConsType', verbose_name='Тип расходного материала')),
            ],
            options={
                'verbose_name': 'Движение расходных материалов',
                'verbose_name_plural': 'Движения расходных материалов',
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('firm', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.Firm', verbose_name='Фирма')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.ConsType', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Расходный материал',
                'verbose_name_plural': 'Расходные материалы',
            },
        ),
        migrations.AddField(
            model_name='moveitem',
            name='type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='name', chained_model_field='type', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='Store.StoreItem'),
        ),
    ]
